Implementation of the Get Involved pate
eclipse-thingweb/website pull request #103
Opened 2024-11-04 02:07 UTC by SergioCasCeb

Added a new documentation page for the "Get Involved" section, which was missing. Currently, this page includes content from the legacy website, and an "Under Construction" sign has been added to indicate that more updates are coming.

Once fully implemented, this will also partially resolve the missing redirect referenced in issue #94.

2024-11-04 15:46 UTC, danielpeintner approved these changes
LGTM, thanks!

2024-11-04 21:43 UTC, egekorkan requested changes

2024-11-05 23:04 UTC, SergioCasCeb commented on get-involved/introduction.md
I did not see this change request. I will get it done tomorrow.

2024-11-06 08:37 UTC, danielpeintner commented on get-involved/introduction.md
Mhh, maybe it does make sense to list all our tools ... what to you think?

2024-11-08 10:50 UTC, egekorkan commented on get-involved/introduction.md
Call today: In order to avoid maintaining two lists, we can simply link to the landing page tools section.

2024-11-08 11:17 UTC, SergioCasCeb commented on get-involved/introduction.md
I removed the components list and added a link to the tools section on the landing page

2024-11-08 11:21 UTC, egekorkan approved these changes

2024-11-08 11:21 UTC, merged