Implementing Google Analytics
eclipse-thingweb/website pull request #74
Opened 2024-04-16 15:18 UTC by SergioCasCeb

This is a new implementation of Google Analytics as well as the required consent banner to handle the necessary Google tags and therefore comply with any Eclipse Google Analytics Policy.

- The default state is always set to deny all tags.
- The consent banner will always show on screen if no previous preferences have been set.
- After accepting or denying the consent banner, the respective Google tags are updated as well as saving the user's preferences on local storage. 
- The User can change their preferences anytime by clicking on the "Manage Cookies" link found on the footer.

2024-04-16 16:23 UTC, danielpeintner commented
FYI: I just noticed that the header image lays *over* the consent banner. I think it should be the other way around...

![image](https://github.com/eclipse-thingweb/website/assets/11281461/b07518bf-30aa-418c-af17-e83ff6290592)

2024-04-16 16:42 UTC, SergioCasCeb commented
> FYI: I just noticed that the header image lays *over* the consent banner. I think it should be the other way around...
> 
> ![image](https://github.com/eclipse-thingweb/website/assets/11281461/b07518bf-30aa-418c-af17-e83ff6290592)
> 

Interesting, I didn't notice that while testing. But most likely because my viewport is too big for the banner to even reach the header. I will fix it. Thank you 😁

2024-04-16 18:21 UTC, SergioCasCeb commented
That should do the trick, nonetheless. If the plan is to stick to Hugo, I believe it would be really necessary to refactor the project, not just in regards to utilizing the newest version of Hugo but also revising how the styling is being handled.

2024-04-16 19:10 UTC, egekorkan commented
The PR looks good. It is not going to the main branch anyways but to my existing PR. If some give the OK, I will merge it and then trigger Eclipse Webmaster on the other PR.

2024-04-16 21:38 UTC, SergioCasCeb commented
**Google Analytics and Consent Process**

- As a default, if the user has not set any consent preferences, the local storage should be empty and therefore all the Google Tags are set to denied as a default. Meaning that nothing is tracked.

![Screenshot 2024-04-16 215204](https://github.com/eclipse-thingweb/website/assets/72516762/a83d5189-03e6-4a67-93f0-b8bbaadab49b)
![Screenshot 2024-04-16 215233](https://github.com/eclipse-thingweb/website/assets/72516762/fb1a3f96-0141-4258-8e20-cc39c730ec07)

- If the user decides to decline tracking, the banner is then hidden, Google Tags remain in their default denied state, and the user's preference is saved in Local Storage for future reference.

![Screenshot 2024-04-16 221546](https://github.com/eclipse-thingweb/website/assets/72516762/2df9981c-0cb6-41ec-ace5-74c87222b4e5)
![Screenshot 2024-04-16 221623](https://github.com/eclipse-thingweb/website/assets/72516762/af9ddd1e-f1c1-4362-84f9-fd965c2f4c04)

- Finally, if the user decides to allow tracking, as before, the banner is then hidden, Google Tags are updated to allow only `analytics_storage`, and the user's preference is saved to be used as the new default state.

![Screenshot 2024-04-16 233108](https://github.com/eclipse-thingweb/website/assets/72516762/d9ed9d81-f80b-456c-b3cb-be7a43a1550e)
![Screenshot 2024-04-16 233127](https://github.com/eclipse-thingweb/website/assets/72516762/deb4b732-da5f-4c80-858c-5988bc465e2c)

- Of course, the user can change their preferences anytime by clicking on the "Manage Cookies" link found on the footer.

2024-04-17 07:11 UTC, danielpeintner commented
The PR seems fine to me as well 👍.

Once the consent banner is hidden it might be difficult for users to find the "Manage Cookies" link in the footer. Anyhow, I don't have a good alternative other than creating a dedicated cookie button in the bottom right corner or so... not sure if this might work better.

2024-04-17 21:44 UTC, SergioCasCeb commented
> The PR seems fine to me as well 👍.
> 
> Once the consent banner is hidden it might be difficult for users to find the "Manage Cookies" link in the footer. Anyhow, I don't have a good alternative other than creating a dedicated cookie button in the bottom right corner or so... not sure if this might work better.
> 
> An example what I mean can be seen on https://www.cookieyes.com/documentation/change-cookie-consent-using-cookieyes/

That could be a nice, simple solution. For the moment we could also specify on the banner that the user preferences can always be changed/updated on the link below.

2024-04-17 21:46 UTC, egekorkan commented
> For the moment we could also specify on the banner that the user preferences can always be changed/updated on the link below.

This would be actually good. Could you add it to the PR?

2024-04-19 09:09 UTC, danielpeintner commented
BTW, the name of the PR "Implementing Google Analytics" does not convey the actual content. I think it should rather say "Implementing Consent Banner"

2024-04-19 09:42 UTC, egekorkan requested changes

2024-04-19 09:42 UTC, egekorkan commented on themes/thingweb/layouts/partials/footer.html
> +                <h4>Google Analytics Consent</h4>
```suggestion
                <h4>Site Analytics Consent</h4>
```

2024-04-19 09:42 UTC, egekorkan commented on themes/thingweb/layouts/partials/footer.html
> +                        href="https://www.eclipse.org/legal/privacy.php">Eclipse Foundation Privacy Policy.</a></p>
```suggestion
                        href="https://www.eclipse.org/legal/privacy.php">Eclipse Foundation Privacy Policy.</a></p>
<p>You can change your preference later at the <b>Manage Consent</b> link in the footer.</p>
```

2024-04-19 09:44 UTC, egekorkan commented
We checked in the commiter's call and after those two small changes, we can merge and ping Webmaster

2024-04-19 11:43 UTC, merged

2024-04-22 13:03 UTC, egekorkan commented
> @egekorkan the PR goes againts [eclipse-thingweb:egekorkan-patch-2](https://github.com/eclipse-thingweb/website/tree/egekorkan-patch-2)

Yes this is just updating the PR I already had. That PR is linked in the Eclipse helpdesk