Thingweb website redesign
eclipse-thingweb/website pull request #82
Opened 2024-10-04 12:29 UTC by SergioCasCeb

Website preview: [Thingweb website](https://thingweb.netlify.app)

Everything in this PR:

* Overall new design for the website utilizing Docusaurus
* New landing page
  * Hero banner
  * Value proposition section
  * Worklfows section (still under construction)
  * Tools section
  * Services section
  * Community section (Adopters list)
* Docs page for documentation
* Services page and hands-on page (currently just a copy of the old one)

Also coming in this PR:
* Google Analytics banner
* Feeback prompt/icon

2024-10-04 12:36 UTC, egekorkan commented on misc/designcrowd/fonts.zip
@danielpeintner this should not be needed anymore right? It is mentioned at https://github.com/eclipse-thingweb/website/pull/67#issuecomment-1911811144 but it is old

2024-10-07 09:55 UTC, danielpeintner commented on misc/designcrowd/fonts.zip
I agree, it should not be needed anymore. Does it make sens to store them "somewhere".. or is the GitHub archive enough?

2024-10-07 10:16 UTC, danielpeintner requested changes
Find some more comments below... based on the the rendered version at https://thingweb.netlify.app/

## Intendation in code snippets broken.
e.g.,, https://thingweb.netlify.app/hands-on/intro-raspberry/

![image](https://github.com/user-attachments/assets/55456086-db6f-4963-a8f8-ec300dd1d8e0)

There are more places...

## Spaces in Services missing
![image](https://github.com/user-attachments/assets/8fec3109-e6f7-4317-b48d-f848199e714c)

There are more..

## Navigation sub navi
e.g. in Hands-on for example etc

## Shall we open links in new window/tab or not?
We should be consistent..
for example  Adopters don't open in new page.. playground does.. not sure what we can do. Do know that Adapteres is code from Eclipse

## TD specification link

At the moment it points to dated URI, https://www.w3.org/TR/2023/REC-wot-thing-description11-20231205/
All the other don't do that.. I think we should use https://www.w3.org/TR/wot-thing-description11/ instead...

## Hyphens in tools
Tools section.. Sometimes with dash between name, sometimes not 
dart-wot vs dart_wot, playground without hyphen at all? Maybe also without TD ?

## Draggable moving parts
Would be nice if we find a good way to drag manually the sliders...


## General

I am okay with merging soon and fixing issues afterwards and once the popup...

2024-10-11 09:30 UTC, egekorkan commented on CONTRIBUTING.md
This will be restored

2024-10-11 09:31 UTC, egekorkan commented
@danielpeintner your feedback is now implemented and deployed.

2024-10-11 09:55 UTC, egekorkan commented
Descriptions for tools can be picked from https://github.com/eclipse-thingweb/.eclipsefdn/pull/29

2024-10-11 09:58 UTC, egekorkan commented on src/components/FeedbackPrompt/index.js
> +                <a href='https://github.com/eclipse-thingweb/website' target='_blank'>
```suggestion
                <a href='https://github.com/orgs/eclipse-thingweb/discussions/8'>
```

2024-10-14 13:58 UTC, danielpeintner commented
> @danielpeintner your feedback is now implemented and deployed.
> 
> Regarding hyphens: We have reached a compromised resolution that we are happy with, which is removing the hyphen and putting a space instead.

Thanks 👍

In some code snippets the code seems still a bit odd and inconsistent (different indentation for examples that follow each other etc). Maybe it was there before on the old website. If there would be an autoformatter it might be even better ... anyhow.. I think it is fine as is!

BTW. the "leave us some feedback" banner takes quite a bit of space on smaller screen sizes and hides other content? Do we actually need that at all?
Anyhow, again no really strong opinion.

2024-10-21 13:32 UTC, egekorkan commented on src/components/HomogeneousWorkflow/index.js
I think we can change this to "SDK". Then we can merge and find a better name later on.

2024-10-21 13:32 UTC, egekorkan commented on src/components/WorkflowsSection/index.js
> +                                <p className={styles.description}>Easily manage a fleet of heterogeneous devices and orchestrate applications at scale.</p>
Can be called "Platform"

2024-10-21 17:47 UTC, egekorkan commented
This is now good to go. I will resolve conflicts and merge

2024-10-21 18:51 UTC, merged